### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by Arystanbek-kkwiki** [Krinkle/mw-gadget-rtrc#68] opened 2016-10-08 09:05 UTC
Please add RTRC tab on right side of Special:RecentChanges.
![2016-10-08-recent changes - wikipedia the free encyclopedia](https://cloud.githubusercontent.com/assets/5893711/19211952/275806b8-8d6a-11e6-879c-4dc64a62f449.png)

**Comment by he7d3r** [comment] 2016-10-08 12:01
:+1:

**Comment by Arystanbek-kkwiki** [comment] 2016-10-08 14:25
Thank you very much. [https://kk.wikipedia.org/w/index.php?title=МедиаУики:Common.js&curid=4278&diff=2483773&oldid=2483599 Done!](url)

**Comment by Krinkle** [comment] 2016-10-11 22:05
(This was a duplicate of #11.)

**Closed by Krinkle** 2016-10-11 22:05 UTC
Labels: enhancement
